<a href="https://colab.research.google.com/github/yemioz/Numerical-Methods-Projects/blob/main/sys-linear-equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Systems of Linear Equation Solving

This notebook is an attempt at implementing from scratch Gauss-Jordan Elimination. 

Below are imported packages that will support the functions and expressions needed for the coding throughout this project.

In [1]:
import math
import numpy as np

### Gauss-Jordan Method

Gauss-Jordan Elimination is an algorithm that can be used to solve systems of linear equations. It relies upon three elementary row operations one can use on a matrix:

1.Swap the positions of two of the rows.

2.Multiply one of the rows by a scalar.

3.Add or subtract the scalar multiple of one row to another row.


Below are functions for these operations.

In [2]:
def swap_rows(matrix, row1, row2):
  new_matrix = []
  for i in range(len(matrix)):
    if i != row1:
      if i != row2:
        new_matrix.append(matrix[i,:])
      else:
        new_matrix.append(matrix[row1,:])
    else:
      new_matrix.append(matrix[row2,:])
  return np.array(new_matrix)


def add_rows(matrix, target_row, modifier_row, value):
  new_row = matrix[target_row,:] + value*matrix[modifier_row,:]
  new_matrix = []
  for i in range(len(matrix)):
    if i != target_row:
      new_matrix.append(matrix[i,:])
    else:
      new_matrix.append(new_row)
  return np.array(new_matrix)


def constant_mult(matrix, row, value):
  new_row = value*matrix[row,:]
  new_matrix = []
  for i in range(len(matrix)):
    if i != row:
      new_matrix.append(matrix[i,:])
    else:
      new_matrix.append(new_row)
  return np.array(new_matrix)

Our system of equations with three unknowns is:

\begin{align*}
\left\{
\begin{array}{ll}
      -x_1 - 5x_2 - 5x_3 = 2\\
4x_1 - 5x_2 + 4x_3 = 19\\
x_1 + 5x_2 - x_3 = -20
\end{array}
\right.
\end{align*}


We will now use our previously defined functions to perform the Gauss-Jordan process.



In [3]:
matrix = np.array([[-1, -5, -5, 2], [4, -5, 4, 19], [1, 5, -1, -20]])

Below is our system of equations in  matrix form.

In [4]:
matrix

array([[ -1,  -5,  -5,   2],
       [  4,  -5,   4,  19],
       [  1,   5,  -1, -20]])

The first step is $$row_1 \leftrightarrow row_3$$ to get a leading 1.


In [5]:
matrix = swap_rows(matrix, 0, 2)
matrix

array([[  1,   5,  -1, -20],
       [  4,  -5,   4,  19],
       [ -1,  -5,  -5,   2]])

Our second step is: $$row_2 - 4row_1$$

In [6]:
matrix = add_rows(matrix, 1, 0, -4)
matrix

array([[  1,   5,  -1, -20],
       [  0, -25,   8,  99],
       [ -1,  -5,  -5,   2]])

Next:$$row_3 + row_1$$

In [7]:
matrix = add_rows(matrix, 2, 0, 1)
matrix

array([[  1,   5,  -1, -20],
       [  0, -25,   8,  99],
       [  0,   0,  -6, -18]])

Then:  $$-\frac{1}{25}row_2$$

In [8]:
matrix = constant_mult(matrix, 1, -1/25)
matrix

array([[  1.  ,   5.  ,  -1.  , -20.  ],
       [ -0.  ,   1.  ,  -0.32,  -3.96],
       [  0.  ,   0.  ,  -6.  , -18.  ]])

Next: $$-\frac{1}{6}row_3$$

In [9]:
matrix = constant_mult(matrix, 2, -1/6)
matrix

array([[  1.  ,   5.  ,  -1.  , -20.  ],
       [ -0.  ,   1.  ,  -0.32,  -3.96],
       [ -0.  ,  -0.  ,   1.  ,   3.  ]])

Then: $$row_1+row_3$$

In [10]:
matrix = add_rows(matrix, 0, 2, 1)
matrix

array([[  1.  ,   5.  ,   0.  , -17.  ],
       [ -0.  ,   1.  ,  -0.32,  -3.96],
       [ -0.  ,  -0.  ,   1.  ,   3.  ]])

Then: $$row_2+\frac{8}{25}row_3$$

In [11]:
matrix = add_rows(matrix, 1, 2, 8/25)
matrix

array([[  1.,   5.,   0., -17.],
       [ -0.,   1.,   0.,  -3.],
       [ -0.,  -0.,   1.,   3.]])

Our final step: $$row_1-5row_2$$

In [12]:
matrix = add_rows(matrix, 0, 1, -5)
matrix

array([[ 1.,  0.,  0., -2.],
       [-0.,  1.,  0., -3.],
       [-0., -0.,  1.,  3.]])

As you can see, the solution to our system of equations is: $$x_1 = -2, \text{ } x_2 = -3, \text{ } x_3 = 3$$

Now, building our Gauss-Jordan algorithm:

In [13]:
def smallest_pivot(matrix, row):
  element = matrix[row:,row]
  element = np.abs(element)
  spot = np.where(element == min(element))
  return spot[0][0]+row


def gauss_jordan(matrix):
  new_matrix = matrix
  for control in range(len(matrix)):
    spot = smallest_pivot(new_matrix, control)
    new_matrix = swap_rows(new_matrix, spot, control)
    new_matrix = constant_mult(new_matrix, control, 1/control)
    for i in range(0, control):
      new_matrix = add_rows(new_matrix, i, control, -new_matrix[i,control])
    for i in range(control+1, len(matrix)):
      new_matrix = add_rows(new_matrix, i, control, -new_matrix[i,control])
    return np.array(new_matrix)

In [14]:
gauss_jordan(matrix)

ZeroDivisionError: division by zero

The problem with building our algorithm comes when when we find our pivot element and try to change it to a leading one. During the algorithm, we divide by zero, which breaks the method. We followed Dr. Jacob's example and catered it to our functions to try to correct it.

Now inputing the following system into our Gauss-Jordan function,
\begin{align*}
\left\{
\begin{array}{ll}
      x - 2y = 2\\
2x - 4y = 4
\end{array}
\right.
\end{align*}

In [ ]:
B = np.array([[1, -2, 2], [2, -4, 4]])
gauss_jordan(B)

Again, we run into dividing by zero error when trying to change our pivot element into a leading one.

### Findings


While Gauss Jordan feels very intimidating at first, when you break it down, you get only a handful of easy to understand rules and a goal you have to get to. These rules and this goal are all numeric or arithmetic, which are very easily understood by coding languages. Because of this, it's potentially very easy to make a program that solves Gauss Jordan issues.

The thing we struggled with most was getting the program to understand what the goal was, and which of it's options it has to use in order to get to the goal. While it's true that our end point is having every non-diagonal value equal 0, that is easier to explain to a human than to a computer, and determining the correct course of action is even harder than that.